pr: none
trigger:
  batch: true
  branches:
    include:
      - main

steps:
  - task: AzureCLI@2
    displayName: Upload files to Azure Storage Account
    inputs:
      azureSubscription: choreo-shared-frontend-apps-cdn-rg
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        mapfile -t icons < <(find -- * -maxdepth 1 -name "icon.png")
        
        for icon in "${icons[@]}"; do
          az storage blob upload \
            --container-name "choreo-samples/$(dirname "$icon")" \
            --file "$icon" \
            --overwrite true \
            --account-name choreosharedfeappscdn96 \
            --output json | jq '.'
          # avoid throttling
          sleep 5
        done
        
        az storage blob upload \
            --container-name "choreo-samples" \
            --file "index.json" \
            --account-name choreosharedfeappscdn96
