pr: none
trigger:
  batch: true
  branches:
    include:
      - main

variables:
  - group: choreo-samples

steps:
  - task: AzureCLI@2
    displayName: Upload files to Azure Storage Account
    inputs:
      azureSubscription: $(resource_group)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        mapfile -t icons < <(find -- * -maxdepth 1 -name "icon.png")
        
        for icon in "${icons[@]}"; do
          az storage blob upload \
            --container-name "choreo-samples/$(dirname "$icon")" \
            --file "$icon" \
            --overwrite true \
            --account-name "$(storage_account_name)" \
            --output json | jq '.'
          # avoid throttling
          sleep 5
        done
        
        az storage blob upload \
            --container-name "choreo-samples" \
            --file "index.json" \
            --overwrite true \
            --account-name "$(storage_account_name)"
        
        az cdn endpoint purge \
          --content-paths '/*'\
          --profile-name "$(cdn_profile)" \
          --name "$(cdn_endpoint)" \
          --resource-group "$(resource_group)"
